### PR TITLE
Test Python 3.6 on Travis

### PR DESCRIPTION
**Pull request by The-Compiler**
I think that's the default available nowadays.

### CODE REVIEW

**Comment by dbrgn** [comment]
You also need to update `tox.ini`.

If you want you can update your PR to drop Python 2 support, and then test Python 3.5 and either 3.7 or 3.8 in CI / Tox.

**Comment by The-Compiler** [comment]
This seems to run without any update to `tox.ini` - tox has pyXY environments built in. I guess I could update it to use py36 (or py37) by default in `envlist` and drop the unnecessary `[testenv:py35]` environment though.

**Comment by dbrgn** [comment]
Oh, I wasn't aware of that. However, for the users that run tests locally, the Tox config should match the CI config.

**Comment by The-Compiler** [comment]
Updated! I lack the time to look at dropping Python 2 support at the moment, blame my bachelor thesis :wink:

**Comment by dbrgn** [comment]
Thanks. The tox config is still missing for 3.6. But feel free to ignore that, I'll incorporate the changes into a separate PR that drops Python 2 support and tests on 3.5 and 3.7. Thanks anyways for bringing it up!

**Comment by dbrgn** [comment]
See #30. I also dropped TravisCI :tada:

**Comment by The-Compiler** [comment]
Awesome, thanks! :+1:

**Pull request closed without merging**
